name: fast-bleu-actions
on: push

jobs:
  pypi-push:
    name: Push package to Pypi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build package
        run: python setup.py sdist

      - name: Publish a Python distribution to PyPI
        # if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: pypa/gh-action-pypi-publish@release/v1.4.2
        with:
          user: ${{ secrets.PYPI_USER }}
          password: ${{ secrets.PYPI_SECRET }}